### PR TITLE
Remove referential.root

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Comment by elemoine** [comment]
I am fine with this being merged after https://github.com/LI3DS/micmac_li3ds/pull/12.

**Comment by mbredif** [comment]
Ok to merge this after conflict resolution.

**Comment by elemoine** [comment]
@mbredif any reason for `Config` to [have](https://github.com/LI3DS/micmac_li3ds/blob/master/micmac_li3ds/api.py#L389) a `root` key? It looks like `Config` has the same key as `Referential`, which does not look correct to me.

**Comment by elemoine** [comment]
Rebased.

**Pull request merged**
